# Generated by Django 5.0.14 on 2026-05-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='intro_video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo link to a short intro about you (about 60 seconds).'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles_pictures/'),
        ),
    ]
