# Generated by Django 5.0.14 on 2026-05-21 10:35

import backend.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_video',
            field=models.FileField(blank=True, help_text='Optional upload (uses Cloudinary on Render). Max 60 MB, ~1 minute.', null=True, upload_to='project_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), backend.models.validate_demo_video_size]),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo link (recommended, free). Short demo, about 60 seconds.'),
        ),
        migrations.AlterField(
            model_name='skil',
            name='proficiency',
            field=models.IntegerField(),
        ),
    ]
