# Generated by Django 5.0.14 on 2026-05-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_demo_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct image link. Used if set — fixes broken uploads on Render.'),
        ),
    ]
