# Generated by Django 5.0.14 on 2026-05-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Direct link: https://i.imgur.com/xxxxx.jpg (right-click image → Copy image address). Best on Render for the live site.', verbose_name='Cover image URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional file upload. On Render, prefer Cover image URL.', null=True, upload_to='blog/', verbose_name='Cover image (file upload)'),
        ),
    ]
