# Generated by Django 5.0.14 on 2026-05-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cover_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cover_image_url',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
