"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-dev-only-change-in-production",
)

DEBUG = os.getenv("DEBUG", "True").lower() in ("1", "true", "yes")

def _parse_hosts(value):
    hosts = []
    for part in value.split(","):
        host = part.strip().strip('"').strip("'")
        if not host:
            continue
        # Fix copy-paste: "ALLOWED_HOSTS=portfolio-api.onrender.com" as value
        if host.upper().startswith("ALLOWED_HOSTS="):
            host = host.split("=", 1)[1].strip()
        for prefix in ("https://", "http://"):
            if host.startswith(prefix):
                host = host[len(prefix) :].split("/")[0]
        if host:
            hosts.append(host)
    return hosts


_allowed = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = _parse_hosts(_allowed)

# Render injects the real public hostname at runtime
_render_host = (os.getenv("RENDER_EXTERNAL_HOSTNAME") or "").strip()
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)

# Wildcard for any *.onrender.com service (safe on Render only)
if _render_host or os.getenv("RENDER"):
    for host in (".onrender.com",):
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)

# Render sits behind a HTTPS proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

_CLOUDINARY_URL = (os.getenv("CLOUDINARY_URL") or "").strip()
USE_CLOUDINARY = bool(_CLOUDINARY_URL)

_INSTALLED_CORE = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
]

if USE_CLOUDINARY:
    INSTALLED_APPS = [
        *_INSTALLED_CORE,
        "cloudinary_storage",
        "cloudinary",
        "django.contrib.staticfiles",
        "rest_framework",
        "chatbot",
        "corsheaders",
        "core",
        "backend",
        "blog",
        "contact",
    ]
else:
    INSTALLED_APPS = [
        *_INSTALLED_CORE,
        "django.contrib.staticfiles",
        "rest_framework",
        "chatbot",
        "corsheaders",
        "core",
        "backend",
        "blog",
        "contact",
    ]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
]
if not DEBUG:
    MIDDLEWARE.append("whitenoise.middleware.WhiteNoiseMiddleware")
MIDDLEWARE += [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Local dev: USE_POSTGRES=false → SQLite (ignores DATABASE_URL).
# Production (Render): USE_POSTGRES=true + DATABASE_URL from Postgres.

_sqlite_path = BASE_DIR / "db.sqlite3"
_database_url = os.getenv("DATABASE_URL")
_use_postgres = os.getenv("USE_POSTGRES", "").lower() in ("1", "true", "yes")

if _use_postgres and _database_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": _sqlite_path,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

_default_storage = (
    "cloudinary_storage.storage.MediaCloudinaryStorage"
    if USE_CLOUDINARY
    else "django.core.files.storage.FileSystemStorage"
)

_staticfiles_backend = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG
    else "whitenoise.storage.CompressedStaticFilesStorage"
)

STORAGES = {
    "default": {"BACKEND": _default_storage},
    "staticfiles": {"BACKEND": _staticfiles_backend},
}

if USE_CLOUDINARY:
    import cloudinary

    cloudinary.config(secure=True)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Serve uploaded files from Render (no /media/ in production when DEBUG=False by default)
SERVE_MEDIA_FILES = os.getenv("SERVE_MEDIA", "").lower() in (
    "1",
    "true",
    "yes",
) or bool(os.getenv("RENDER"))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

_default_cors = "http://localhost:5173,http://127.0.0.1:5173"
_cors = os.getenv("CORS_ALLOWED_ORIGINS", _default_cors)


def _parse_cors_origins(value):
    origins = []
    for part in value.split(","):
        origin = part.strip().rstrip("/")
        if origin:
            origins.append(origin)
    return origins


CORS_ALLOWED_ORIGINS = _parse_cors_origins(_cors)

# Required for Django admin over HTTPS in production
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)
if _render_host:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_render_host}")

GROQ_API_KEY = (os.getenv("GROQ_API_KEY") or "").strip()